name: Latest Blog Posts

on:
  schedule:
    # Runs every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/marufsarker"
          max_post_count: "5"
          readme_path: "README.md"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          # CORRECTED LINE:
          custom_tag: "BLOG-POSTS" # <--- Use 'custom_tag'
          # Optional: Filter by categories/tags (useful if you want specific posts)
          # categories: "tech,programming" 
          # Optional: Date format
          # date_format: "DD MMMYYYY"
          # Optional: Use a custom template for each post entry (highly customizable)
          # item_template: "<li><a href='{url}'>{title}</a> - {date}</li>"