name: Latest Blog Posts

on:
  schedule:
    # Runs every 24 hours at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: write # This is crucial for the bot to write to your README.md

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4 # Checks out your repository code

      - uses: gautamkrishnar/blog-post-workflow@v1 # The action that fetches and updates
        with:
          feed_list: "https://dev.to/feed/marufsarker" # Your Dev.to RSS feed URL
          max_post_count: "5" # How many latest posts to display
          readme_path: "README.md" # The README file to update
          gh_token: ${{ secrets.GITHUB_TOKEN }} # The special GitHub token (automatically provided)
          # Optional: Filter by categories/tags (useful if you want specific posts)
          # categories: "tech,programming" 
          date_format: "DD MMMYYYY" # Date format for output
          # Custom template for each post entry (highly customizable)
          item_template: "<li><a href='{url}'>{title}</a> - {date}</li>"
          custom_tag: "BLOG-POSTS" # This is important for unique placeholders in README.md
