name: Latest YouTube Videos

on:
  schedule:
    # Runs every 24 hours at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: write # Essential for the bot to write to your README.md

jobs:
  update-readme-with-youtube:
    name: Update README with latest YouTube videos
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4 # Checks out your repository code

      - uses: gautamkrishnar/blog-post-workflow@master # The action that fetches and updates
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCAne1jQhrjTOJ3s3yuAAtcQ" 
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d,yyyy" 
          template: >
            <table><tr><td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline
          committer_email: "mdmarufsarker.mms@gmail.com"
          custom_tag: "YOUTUBE-VIDEOS"
