name: Latest YouTube Videos

on:
  schedule:
    # Runs every 24 hours at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: write # Essential for the bot to write to your README.md

jobs:
  update-readme-with-youtube:
    name: Update README with latest YouTube videos
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4 # Checks out your repository code

      - uses: gautamkrishnar/blog-post-workflow@master # The action that fetches and updates
        with:
          # Your YouTube RSS feed URL
          # IMPORTANT: Make sure this is your actual YouTube channel's RSS feed URL.
          # A common format is: https://www.youtube.com/feeds/videos.xml?channel_id=YOUR_CHANNEL_ID
          # Please replace the URL below with your correct feed.
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCAne1jQhrjTOJ3s3yuAAtcQ" 
          
          # Custom tags to extract data from the YouTube feed
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          # Date format for the output
          date_format: "mmm d,YYYY" 
          # Custom HTML template for each video entry
          template: >
            <table><tr><td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline
          # The committer email for the automated commits
          committer_email: "mdmarufsarker.mms@gmail.com"
          # UNIQUE TAG: This tells the action which specific placeholder comments to use
          custom_tag: "YOUTUBE-VIDEOS"